# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuskersApp', '0004_group_group_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
